<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNaECK1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNaECK1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPNaECK1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPNaECK1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPNaECK1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PNaECK1',
    'container.build_id' => 'fd656579',
    'container.build_time' => 1532709661,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNaECK1');
